version: '3.2'

networks:
    app-network:
        driver: bridge

volumes:
    home-dir:
    db-data:

services:

    web:
        image: artjoker/7.4:nginx
        restart: on-failure
        volumes:
            - ./:/app/
        env_file:
            - .env
        depends_on:
            - php
        ports:
            - 80:80
        networks:
            - app-network

    php:
        image: artjoker/8.1:php-prod
        user: '${USER_ID:-1000}:${GROUP_ID:-1000}'
        restart: on-failure
        volumes:
            - /etc/passwd:/etc/passwd:ro
            - /etc/group:/etc/group:ro
            - ./volumes/home:/home/user:rw
            - ./:/app/
        environment:
            - HOME=/home/user
        env_file:
            - .env
        command: php-fpm --nodaemonize -d "opcache.enable=0" -d "display_startup_errors=On" -d "display_errors=On" -d "error_reporting=E_ALL" -R
        depends_on:
            - redis
            - database
        networks:
            - app-network

    test:
        image: artjoker/8.1:php-dev
        user: '${USER_ID:-1000}:${GROUP_ID:-1000}'
        restart: 'no'
        volumes:
            - /etc/passwd:/etc/passwd:ro
            - /etc/group:/etc/group:ro
            - ./:/app/
        env_file:
            - .env
        environment:
            - XDEBUG_MODE=coverage
        command: php-fpm --nodaemonize -d "opcache.enable=0" -d "display_startup_errors=On" -d "display_errors=On" -d "error_reporting=E_ALL" -R
        depends_on:
            - redis
            - database
        networks:
            - app-network

    queue:
        image: artjoker/8.1:php-prod
        user: '${USER_ID:-1000}:${GROUP_ID:-1000}'
        restart: on-failure
        volumes:
            - /etc/passwd:/etc/passwd:ro
            - /etc/group:/etc/group:ro
            - ./:/app/
        env_file:
            - .env
        command: php /app/artisan queue:work
        depends_on:
            - redis
            - database
        networks:
            - app-network

    cron:
        image: artjoker/8.1:php-prod
        user: '${USER_ID:-1000}:${GROUP_ID:-1000}'
        restart: on-failure
        volumes:
            - /etc/passwd:/etc/passwd:ro
            - /etc/group:/etc/group:ro
            - ./:/app/
        env_file:
            - .env
        command: /usr/local/bin/supercronic /usr/cron/cron.conf
        depends_on:
            - redis
            - database
        networks:
            - app-network

    node:
        image: artjoker/7.4:node
        user: '${USER_ID:-1000}:${GROUP_ID:-1000}'
        restart: on-failure
        command: /start.sh
        volumes:
            - /etc/passwd:/etc/passwd:ro
            - /etc/group:/etc/group:ro
            - ./:/app
        working_dir: /app

    redis:
        image: redis:alpine
        restart: on-failure
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            interval: 15s
            timeout: 3s
            retries: 5
        networks:
            - app-network

    database:
        image: postgres:13-alpine
        restart: on-failure
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres" ]
            interval: 30s
            timeout: 10s
            retries: 5
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=laravel
            - POSTGRES_HOST=database
        volumes:
            - ./docker/init.db:/docker-entrypoint-initdb.d
            - db-data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        networks:
            - app-network
